version: '1'
services:
  - name: clonador
    type: web
    docker:
      image: zenika/alpine-chrome:with-node  # Imagem com Node.js e Chromium
      build:
        commands:
          - apk add --no-cache curl
          - curl -sL https://npmjs.org/install.sh | sh
          - npm install
      run:
        command: npm start
    ports:
      - port: 3000
        protocol: http
    environment:
      - name: PORT
        value: 3000
      - name: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"  # Evita que o Puppeteer tente baixar o Chromium
      - name: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser  # Caminho correto para o Chromium nesta imagem
