version: '1'
services:
  - name: clonador
    type: web
    docker:
      image: ghcr.io/puppeteer/puppeteer:latest  # Imagem oficial com Node.js e Chromium embutido
      build:
        commands:
          - npm ci  # Instala dependências do package-lock.json
      run:
        command: npm start
    ports:
      - port: 3000
        protocol: http
    environment:
      - name: PORT
        value: 3000
      - name: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"  # Evita download adicional (embora não seja estritamente necessário aqui)
