version: '1'
services:
  - name: clonador
    image: node:18
    commands:
      - name: install-dependencies
        command: npm ci
      - name: install-chrome
        command: bash install-chrome.sh
      - name: start-app
        command: npm start
    environment:
      - name: PORT
        value: 3000
    ports:
      - port: 3000
        protocol: http
