version: '1'
services:
  - name: clonador
    type: web
    docker:
      image: node:18  # Imagem base robusta com Node.js
      build:
        commands:
          - apt-get update
          - apt-get install -y chromium  # Instala o Chromium (Debian-based)
          - npm ci  # Instala dependências do package-lock.json
          - echo "Caminho do Chromium:" && which chromium  # Loga o caminho
          - ls -la /usr/bin/chromium || echo "Chromium não encontrado em /usr/bin/chromium"  # Debug
          - ls -la /usr/lib/chromium/chromium || echo "Chromium não encontrado em /usr/lib/chromium/chromium"  # Debug
      run:
        command: npm start
    ports:
      - port: 3000
        protocol: http
    environment:
      - name: PORT
        value: 3000
      - name: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"  # Evita download adicional
      - name: PUPPETEER_EXECUTABLE_PATH
        value: /usr/lib/chromium/chromium  # Caminho padrão em Debian
