version: '1'
services:
  - name: clonador
    type: web
    docker:
      image: node:18-alpine  # Imagem leve com Node.js
      build:
        commands:
          - apk add --no-cache chromium  # Instala o Chromium
          - npm ci  # Instala dependências do package-lock.json
          - echo "Caminho do Chromium:" && which chromium  # Loga o caminho do Chromium
      run:
        command: npm start
    ports:
      - port: 3000
        protocol: http
    environment:
      - name: PORT
        value: 3000
      - name: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"  # Evita download adicional do Chromium
      - name: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium  # Caminho correto no Alpine
