version: '1'
services:
  - name: clonador
    type: web
    docker:
      image: ghcr.io/puppeteer/puppeteer:latest  # Imagem oficial com Node.js e Chromium embutido
      build:
        commands:
          - npm ci  # Instala dependências do package-lock.json
          - echo "Instalando Chrome explicitamente..."
          - npx puppeteer browsers install chrome || echo "Falha ao instalar Chrome"
          - echo "Verificando Chrome instalado:"
          - ls -la /tmp/puppeteer_cache || echo "Diretório /tmp/puppeteer_cache não encontrado"
      run:
        command: npm start
    ports:
      - port: 3000
        protocol: http
    environment:
      - name: PORT
        value: 3000
      - name: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"  # Evita download duplicado
      - name: PUPPETEER_CACHE_DIR
        value: /tmp/puppeteer_cache  # Diretório gravável para o cache
