version: '1'
services:
  - name: clonador
    type: web
    docker:
      image: node:18
      build:
        commands:
          - apt-get update
          - apt-get install -y chromium
          - npm ci
      run:
        command: npm start
    ports:
      - port: 3000
        protocol: http
    environment:
      - name: PORT
        value: 3000
      - name: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
